services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    image: jenkins-custom:latest
    container_name: jenkins
    environment:
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD:-admin123}
      - SONARQUBE_URL=http://sonarqube:9000
      - SONAR_TOKEN=${SONAR_TOKEN:-placeholder}
      - JENKINS_URL=http://${JENKINS_HOST:-localhost}
      - CASC_JENKINS_CONFIG=/usr/share/jenkins/ref/casc.yaml
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Xms256m -Xmx1024m
    ports:
      - "80:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
    depends_on:
      - sonarqube
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8080/login || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 20
      start_period: 300s

  sonarqube:
    image: sonarqube:9.9.4-community
    container_name: sonarqube
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9000:9000"
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9000/api/system/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 180s

  db:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sonar"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  jenkins-data:
    name: jenkins-data
  sonarqube_conf:
    name: sonarqube_conf
  sonarqube_data:
    name: sonarqube_data
  sonarqube_extensions:
    name: sonarqube_extensions
  postgresql:
    name: postgresql
  postgresql_data:
    name: postgresql_data
